# Generated by Django 4.1.6 on 2023-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_candidate_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('requirement', models.CharField(max_length=20)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
    ]
