# Generated by Django 4.1.6 on 2024-12-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_mandate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='user',
        ),
    ]
