# Generated by Django 4.1.6 on 2024-12-08 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_mandate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to=settings.AUTH_USER_MODEL),
        ),
    ]
